### ISSUE TITLE
Errors in downloading from skullsecurity.org during installation

### ISSUE THREAD

**Issue by wkwi2r** [inab/WfExS-backend#131]
I've pulled the image using `docker pull ghcr.io/inab/wfexs-backend:1.0.0rc1`

When I run the below command

```
docker run --rm -ti \
  -u $(id -u):$(id -g) \
  -v ./SING_in_DOCKER_dirs/side_caches:/.cache \
  ghcr.io/inab/wfexs-backend:1.0.0rc1 \
  WfExS-backend populate-side-caches
```

I encountered the following error

```
wfexs_backend.cache_handler.CacheHandlerException: Cannot download content from http://downloads.skullsecurity.org/passwords/cain.txt.bz2 to 4c5dff6d129fe6f5575621759078a793b529da14 (while processing http://downloads.skullsecurity.org/passwords/cain.txt.bz2) (temp file /.cache/es.elixir.WfExSPassGenSingleton/caching-8dfbdd74-ffd9-402c-8aec-78e83c84aca9): <urlopen error [Errno 110] Connection timed out>
```

This is due to our corporate network blocking `skullsecurity.org`

When I switched to use my personal internet connection and repeat the command again, the following error occurred

```
wfexs_backend.cache_handler.CacheHandlerException: Cannot download content from http://downloads.skullsecurity.org/passwords/cain.txt.bz2 to 4c5dff6d129fe6f5575621759078a793b529da14 (while processing http://downloads.skullsecurity.org/passwords/cain.txt.bz2) (temp file /.cache/es.elixir.WfExSPassGenSingleton/caching-f1e8f648-1ff5-4e1e-a2f1-b91f69dab0aa): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)>
```

Any suggestion to resolve this?

**Comment by jmfernandez** [comment]
Hi! Yes, as you have already pinpointed, the issue is that side caches population is depending on http://downloads.skullsecurity.org/passwords/cain.txt.bz2 , which is redirected to https://downloads.skullsecurity.org/passwords/cain.txt.bz2 . But as the server certificate expired past November 24th , both the corporate network and Python urlopen are complaining with a very good reason in their own ways.

Although there are ways to teach Python to ignore expired certificates, it is a bad security practice to do it. So, I'm searching for a substitute URL with the same or similar contents to be used, in order to replace the originally used source.

**Comment by jmfernandez** [comment]
I have just released a new docker image with the changes to use a different URL for the very same word list , as well as some adjustments in the behaviour of the side caches population when some of the word lists is unreachable by any reason.

So, @wkwi2r , could you test the new released image, please?

**Comment by wkwi2r** [comment]
> I have just released a new docker image with the changes to use a different URL for the very same word list , as well as some adjustments in the behaviour of the side caches population when some of the word lists is unreachable by any reason.
> 
> So, @wkwi2r , could you test the new released image, please?

It seems the rc2 image is still running the old code. I'm not so familiar with the source still, am wondering if the `wfexs_checkout` in `container_recipes\Dockerfile` need to be updated with the new commit tag?

**Comment by jmfernandez** [comment]
I can confirm there is an issue in the GitHub CI workflow which builds the images. I have found the possible reason, and I am testing it right now

**Comment by jmfernandez** [comment]
The issue with the container image CI workflow has been fixed. After merging the fixes, I removed both the old image and tag, and I re-tagged the source code, and a new automatically generated image was pushed by the CI workflow. So, in order to get a fresh image you have to purge your local cache just running:

```bash
docker rmi ghcr.io/inab/wfexs-backend:1.0.0rc2
```

before trying again the command.

**Comment by jmfernandez** [comment]
@wkwi2r Could you confirm the re-generated image does not have the issue, please?

**Comment by wkwi2r** [comment]
> @wkwi2r Could you confirm the re-generated image does not have the issue, please?

The new RC2 works (as shown below), thanks. One observation is there's a big gap (over 10 minutes) between `Populating passphrase generator cache` and `Populating common JSON-LD contexts cache`, is this normal duration?
```
Status: Downloaded newer image for ghcr.io/inab/wfexs-backend:1.0.0rc2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
useradd warning: dynuser's uid 501 outside of the UID_MIN 1000 and UID_MAX 60000 range.
2024-12-06 04:42:00,190 - [INFO] Populating passphrase generator cache (lists of words)
2024-12-06 04:54:51,665 - [INFO] Populating common JSON-LD contexts cache (needed for offline JSON-LD parsing)
/usr/local/lib/python3.12/site-packages/pyld/jsonld.py:5050: SyntaxWarning: terms beginning with "@" are reserved for future use and ignored
  warnings.warn(
2024-12-06 04:54:57,219 - [INFO] Populating list of licences cache (list fetched from SPDX)
```

**Comment by jmfernandez** [comment]
Yes, populating passphrase generator cache is slow because most of the lists of words come from Wiktionary API. WfExS-backend fetches lists of English, Spanish and Catalonian nouns and adjectives, used for the generation of random passphrases and names of staged working directories.

Side caches population step is needed only once. Once populated, the directory can be safely shared in read only mode among all the installations you want. Even more, as the directory is relocatable, it can be copied to a read-only shared volume in any other place.
